"use client";
import Header from "@/components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer";
import { Provider } from "react-redux";
import store from "@/store";
import Mayapp from "./Myapp";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ac-movie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Header />
          <Mayapp>{children}</Mayapp>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
